/** GENERATED by sonaloop-design/scripts/gen-tokens.mjs from tokens.data.mjs. Do not edit.
 * Tailwind preset — colours (CSS-var driven, theme-aware via [data-theme]), the always-dark
 * "dusk" ladder, fonts and the quiet hairline. Consume it in tailwind.config:
 *   import preset from '../sonaloop-design/tailwind-preset.js'; … presets: [preset]
 * Colour VALUES live in styles/tokens.css; this only declares the Tailwind shape. */
export default {
  theme: {
    extend: {
      borderColor: { DEFAULT: 'rgb(var(--line) / 0.1)' },
      colors: {
        paper: { DEFAULT: 'rgb(var(--paper) / <alpha-value>)', dark: 'rgb(var(--paper-2) / <alpha-value>)' },
        ink: { DEFAULT: 'rgb(var(--ink) / <alpha-value>)', soft: 'rgb(var(--ink-2) / <alpha-value>)' },
        line: 'rgb(var(--line) / <alpha-value>)',
        blueprint: { deep: 'rgb(var(--blueprint-deep) / <alpha-value>)', DEFAULT: 'rgb(var(--blueprint) / <alpha-value>)', light: 'rgb(var(--blueprint-2) / <alpha-value>)', soft: 'rgb(var(--blueprint-3) / <alpha-value>)' },
        scan: { DEFAULT: 'rgb(var(--scan-blue) / <alpha-value>)', glow: 'rgb(var(--scan-glow) / <alpha-value>)' },
        gold: { DEFAULT: 'rgb(var(--gold) / <alpha-value>)', soft: 'rgb(var(--gold-2) / <alpha-value>)' },
        // Always dark (hero bg / footer) — never themed; the canonical cool dark ladder.
        dusk: { DEFAULT: '#101113', mid: '#16171a', light: '#1c1d21' },
      },
      fontFamily: {
        serif: ["\"Sona\"", "\"Geist\"", "\"Inter\"", "system-ui", "sans-serif"],
        sans: ["\"Sona\"", "\"Geist\"", "\"Inter\"", "system-ui", "sans-serif"],
        mono: ["\"Sona Mono\"", "\"Geist Mono\"", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        pixel: ["\"Sona Pixel\"", "\"Geist Pixel\"", "ui-monospace", "monospace"],
      },
    },
  },
};
