"""persona-icons — GENERATED by scripts/gen.mjs. Do not edit.

Source of truth: ../../icons.data.mjs

Single icon library shared with persona-website (React). Here it renders to
SVG-string markup for server-rendered HTML.

    from persona_icons import icon, hifi
    icon("search")        # -> '<svg class="ic" viewBox="0 0 24 24">...</svg>'
    icon("star")          # -> '<svg class="ic star" ...>'  (extra class from data)
    hifi("persona", 64)   # -> standalone 64px display icon

Regular icons carry geometry only; stroke/size come from the host CSS rule
`svg.ic` (persona-council ships one). Hifi icons inline their own stroke
attributes so they render without any CSS.
"""

from __future__ import annotations

__all__ = ["REGULAR", "HIFI", "icon", "hifi", "names", "hifi_names"]

# name -> {"body": inner SVG markup, "cls": optional extra CSS class}
REGULAR: dict[str, dict[str, str | None]] = {
    "overview": {"body": "<rect x=\"3\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"14\" y=\"3\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"14\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.5\"/><rect x=\"3\" y=\"14\" width=\"7\" height=\"7\" rx=\"1.5\"/>", "cls": None},
    "personas": {"body": "<circle cx=\"9\" cy=\"8\" r=\"3.2\"/><path d=\"M3.5 19a5.5 5.5 0 0 1 11 0\"/><path d=\"M16 5.2a3 3 0 0 1 0 5.6\"/><path d=\"M17.5 19a5.5 5.5 0 0 0-3-4.9\"/>", "cls": None},
    "councils": {"body": "<path d=\"M21 11.5a8.5 8.5 0 0 1-12.5 7.5L4 20l1-4.5A8.5 8.5 0 1 1 21 11.5z\"/>", "cls": None},
    "syntheses": {"body": "<path d=\"M12 3l9 5-9 5-9-5 9-5z\"/><path d=\"M3 13l9 5 9-5\"/>", "cls": None},
    "projects": {"body": "<circle cx=\"6\" cy=\"6\" r=\"2.5\"/><circle cx=\"18\" cy=\"6\" r=\"2.5\"/><circle cx=\"12\" cy=\"18\" r=\"2.5\"/><path d=\"M8 7l8 0M7 8l4 8M17 8l-4 8\"/>", "cls": None},
    "memory": {"body": "<path d=\"M12 3a4 4 0 0 0-4 4 3.5 3.5 0 0 0-1 6.8V17a3 3 0 0 0 5 2 3 3 0 0 0 5-2v-3.2A3.5 3.5 0 0 0 16 7a4 4 0 0 0-4-4z\"/>", "cls": None},
    "panel": {"body": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"16\" rx=\"2\"/><path d=\"M9 4v16\"/>", "cls": None},
    "settings": {"body": "<circle cx=\"12\" cy=\"12\" r=\"3\"/><path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z\"/>", "cls": None},
    "sun": {"body": "<circle cx=\"12\" cy=\"12\" r=\"4\"/><path d=\"M12 2v2M12 20v2M2 12h2M20 12h2M5 5l1.4 1.4M17.6 17.6L19 19M19 5l-1.4 1.4M6.4 17.6L5 19\"/>", "cls": None},
    "moon": {"body": "<path d=\"M20 14.5A8 8 0 1 1 9.5 4a6.3 6.3 0 0 0 10.5 10.5z\"/>", "cls": None},
    "monitor": {"body": "<rect x=\"3\" y=\"4\" width=\"18\" height=\"12\" rx=\"2\"/><path d=\"M9 20h6M12 16v4\"/>", "cls": None},
    "chevron": {"body": "<path d=\"M6 9l6 6 6-6\"/>", "cls": None},
    "back": {"body": "<path d=\"M15 18l-6-6 6-6\"/>", "cls": None},
    "analytics": {"body": "<path d=\"M3 21h18\"/><rect x=\"5\" y=\"11\" width=\"3.4\" height=\"7\" rx=\"1\"/><rect x=\"10.3\" y=\"6\" width=\"3.4\" height=\"12\" rx=\"1\"/><rect x=\"15.6\" y=\"13\" width=\"3.4\" height=\"5\" rx=\"1\"/>", "cls": None},
    "star": {"body": "<path d=\"M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.8L12 17.9 6.8 20.6l1-5.8L3.5 9.7l5.9-.9z\"/>", "cls": "star"},
    "bulb": {"body": "<path d=\"M9 18h6M10 21h4\"/><path d=\"M12 3a6 6 0 0 0-3.8 10.6c.5.5.8 1 .8 1.6V16h6v-.8c0-.6.3-1.1.8-1.6A6 6 0 0 0 12 3z\"/>", "cls": None},
    "target": {"body": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><circle cx=\"12\" cy=\"12\" r=\"4.5\"/><circle cx=\"12\" cy=\"12\" r=\"1\"/>", "cls": None},
    "compass": {"body": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M15.6 8.4l-2 5.2-5.2 2 2-5.2z\"/>", "cls": None},
    "search": {"body": "<circle cx=\"11\" cy=\"11\" r=\"7\"/><path d=\"M21 21l-4.3-4.3\"/>", "cls": None},
    "check": {"body": "<path d=\"M5 12.5l4.5 4.5L19 7\"/>", "cls": None},
    "circle": {"body": "<circle cx=\"12\" cy=\"12\" r=\"7.5\"/>", "cls": None},
    "half": {"body": "<circle cx=\"12\" cy=\"12\" r=\"7.5\"/><path d=\"M12 4.5a7.5 7.5 0 0 1 0 15z\" fill=\"currentColor\" stroke=\"none\"/>", "cls": None},
    "alert": {"body": "<path d=\"M12 4.5v8.5\"/><circle cx=\"12\" cy=\"17.6\" r=\"0.7\" fill=\"currentColor\" stroke=\"none\"/>", "cls": None},
    "close": {"body": "<path d=\"M6 6l12 12M18 6L6 18\"/>", "cls": None},
    "plus": {"body": "<path d=\"M12 5v14M5 12h14\"/>", "cls": None},
    "external": {"body": "<path d=\"M14 4h6v6\"/><path d=\"M20 4l-9 9\"/><path d=\"M18 13v5a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h5\"/>", "cls": None},
    "thumbsup": {"body": "<path d=\"M7 11v8a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-7a1 1 0 0 1 1-1h3z\"/><path d=\"M7 11l4.2-7.4a1.8 1.8 0 0 1 3.2 1.4L13.5 9H19a2 2 0 0 1 2 2.3l-1.1 6.5A2 2 0 0 1 17.9 20H7z\"/>", "cls": None},
    "warning": {"body": "<path d=\"M10.3 4.3 1.8 19a2 2 0 0 0 1.7 3h16.8a2 2 0 0 0 1.7-3L13.7 4.3a2 2 0 0 0-3.4 0z\"/><path d=\"M12 9.5v4\"/><circle cx=\"12\" cy=\"17.3\" r=\"0.6\" fill=\"currentColor\" stroke=\"none\"/>", "cls": None},
    "dot": {"body": "<circle cx=\"12\" cy=\"12\" r=\"5\" fill=\"currentColor\" stroke=\"none\"/>", "cls": None},
    "diamond": {"body": "<path d=\"M12 3l9 9-9 9-9-9z\"/>", "cls": None},
    "diamondFilled": {"body": "<path d=\"M12 3l9 9-9 9-9-9z\" fill=\"currentColor\"/>", "cls": None},
    "caretRight": {"body": "<path d=\"M9 5l7 7-7 7z\" fill=\"currentColor\" stroke=\"none\"/>", "cls": None},
    "arrowRight": {"body": "<path d=\"M4 12h14M13 6l6 6-6 6\"/>", "cls": None},
    "square": {"body": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/>", "cls": None},
    "squareSplit": {"body": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/><rect x=\"8.5\" y=\"8.5\" width=\"7\" height=\"7\" rx=\"1\" fill=\"currentColor\"/>", "cls": None},
    "squareRows": {"body": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/><path d=\"M4 9.3h16M4 14.6h16\"/>", "cls": None},
    "squareCols": {"body": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/><path d=\"M9.3 4v16M14.6 4v16\"/>", "cls": None},
    "squareGrid": {"body": "<rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2.5\"/><path d=\"M12 4v16M4 12h16\"/>", "cls": None},
    "rectangle": {"body": "<rect x=\"3\" y=\"8\" width=\"18\" height=\"8\" rx=\"2\"/>", "cls": None},
    "exchange": {"body": "<path d=\"M4 9h14l-3.5-3.5M20 15H6l3.5 3.5\"/>", "cls": None},
    "wave": {"body": "<path d=\"M3 12c1.5-4 4.5-4 6 0s4.5 4 6 0 4.5-4 6 0\"/>", "cls": None},
    "pencil": {"body": "<path d=\"M4 20l1-4L16 5l3 3L8 19z\"/><path d=\"M14 7l3 3\"/>", "cls": None},
}

# name -> inner SVG markup (48x48, self-styled)
HIFI: dict[str, str] = {
    "overview": "<rect x=\"7\" y=\"7\" width=\"15\" height=\"15\" rx=\"3.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><rect x=\"26\" y=\"7\" width=\"15\" height=\"15\" rx=\"3.5\" stroke-width=\"2\"/><rect x=\"26\" y=\"26\" width=\"15\" height=\"15\" rx=\"3.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><rect x=\"7\" y=\"26\" width=\"15\" height=\"15\" rx=\"3.5\" stroke-width=\"2\"/>",
    "personas": "<circle cx=\"18\" cy=\"17\" r=\"6.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M6 40a12 12 0 0 1 24 0z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M33 11.5a6 6 0 0 1 0 11\" stroke-width=\"1.75\"/><path d=\"M34 40a12 12 0 0 0-6.5-10.6\" stroke-width=\"1.75\"/>",
    "councils": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M9 19a8 8 0 0 1 8-8h14a8 8 0 0 1 8 8v6a8 8 0 0 1-8 8H20l-7 6v-6.6A8 8 0 0 1 9 25z\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/><circle cx=\"18\" cy=\"22\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"24\" cy=\"22\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"30\" cy=\"22\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\"/>",
    "syntheses": "<path d=\"M24 6l18 10-18 10L6 16z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M6 24l18 10 18-10\" stroke-width=\"1.75\"/><path d=\"M6 32l18 10 18-10\" stroke-width=\"1.75\" stroke-opacity=\"0.55\"/>",
    "projects": "<circle cx=\"12\" cy=\"13\" r=\"4.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><circle cx=\"36\" cy=\"13\" r=\"4.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><circle cx=\"24\" cy=\"36\" r=\"5.5\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke-width=\"2\"/><path d=\"M16.5 13h15M15 17l7 14M33 17l-7 14\" stroke-width=\"1.75\"/>",
    "memory": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M24 8a7 7 0 0 0-7 7 6 6 0 0 0-1.6 11.8V31a5 5 0 0 0 8.6 3.5A5 5 0 0 0 32.6 31v-4.2A6 6 0 0 0 31 15a7 7 0 0 0-7-7z\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/><path d=\"M24 8v30\" stroke-width=\"1.25\" stroke-opacity=\"0.5\"/><path d=\"M24 17h5M24 24h-6M24 31h5\" stroke-width=\"1.25\" stroke-opacity=\"0.5\"/>",
    "panel": "<rect x=\"6\" y=\"9\" width=\"36\" height=\"30\" rx=\"4\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M19 9v30\" stroke-width=\"1.75\"/><path d=\"M10.5 16.5h4.5M10.5 22h4.5M10.5 27.5h4.5\" stroke-width=\"1.5\" stroke-opacity=\"0.6\"/>",
    "settings": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><circle cx=\"24\" cy=\"24\" r=\"6.5\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke-width=\"2\"/><path d=\"M24 6v6.5M24 35.5V42M6 24h6.5M35.5 24H42M11.3 11.3l4.6 4.6M32.1 32.1l4.6 4.6M36.7 11.3l-4.6 4.6M15.9 32.1l-4.6 4.6\" stroke-width=\"1.75\"/>",
    "sun": "<circle cx=\"24\" cy=\"24\" r=\"8.5\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke-width=\"2\"/><path d=\"M24 4v6M24 38v6M4 24h6M38 24h6M9.9 9.9l4.3 4.3M33.8 33.8l4.3 4.3M38.1 9.9l-4.3 4.3M14.2 33.8l-4.3 4.3\" stroke-width=\"1.75\"/>",
    "moon": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M40 29A16 16 0 1 1 19 8a12.6 12.6 0 0 0 21 21z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/>",
    "monitor": "<rect x=\"5\" y=\"8\" width=\"38\" height=\"26\" rx=\"4\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/><path d=\"M18 40h12\" stroke-width=\"2\"/><path d=\"M24 34v6\" stroke-width=\"1.75\"/>",
    "chevron": "<path d=\"M12 13l12 11 12-11\" stroke-width=\"1.75\" stroke-opacity=\"0.4\"/><path d=\"M12 24l12 11 12-11\" stroke-width=\"2.5\"/>",
    "back": "<path d=\"M31 12L19 24l12 12\" stroke-width=\"2.5\"/><path d=\"M22 12L10 24l12 12\" stroke-width=\"1.75\" stroke-opacity=\"0.4\"/>",
    "analytics": "<path d=\"M6 42h36\" stroke-width=\"2\"/><rect x=\"9\" y=\"22\" width=\"8\" height=\"14\" rx=\"1.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><rect x=\"20\" y=\"11\" width=\"8\" height=\"25\" rx=\"1.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><rect x=\"31\" y=\"27\" width=\"8\" height=\"9\" rx=\"1.5\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/>",
    "star": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.04\" stroke=\"none\"/><path d=\"M24 7l5.2 10.5 11.6 1.7-8.4 8.2 2 11.6L24 35.4 13.6 41l2-11.6L7.2 21.2l11.6-1.7z\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke-width=\"2\"/>",
    "bulb": "<circle cx=\"24\" cy=\"20\" r=\"18\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M24 8a11 11 0 0 0-7 19.5c1 .9 1.6 1.9 1.6 3V32h10.8v-1.5c0-1.1.6-2.1 1.6-3A11 11 0 0 0 24 8z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M18.6 36h10.8M20.5 40h7\" stroke-width=\"1.75\"/><path d=\"M24 18l2.2 4.4 4.8.7-3.5 3.4.8 4.8L24 29l-4.3 2.3.8-4.8-3.5-3.4 4.8-.7z\" stroke-width=\"1.1\" stroke-opacity=\"0.65\"/>",
    "target": "<circle cx=\"24\" cy=\"24\" r=\"18\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke-width=\"2\"/><circle cx=\"24\" cy=\"24\" r=\"11\" stroke-width=\"1.75\"/><circle cx=\"24\" cy=\"24\" r=\"4\" fill=\"currentColor\" fill-opacity=\"0.2\" stroke-width=\"1.5\"/>",
    "compass": "<circle cx=\"24\" cy=\"24\" r=\"19\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke-width=\"2\"/><path d=\"M31 17l-4 10-10 4 4-10z\" fill=\"currentColor\" fill-opacity=\"0.12\" stroke-width=\"1.75\"/><circle cx=\"24\" cy=\"24\" r=\"1.8\" fill=\"currentColor\" stroke=\"none\"/>",
    "search": "<circle cx=\"21\" cy=\"21\" r=\"14\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M31.5 31.5L42 42\" stroke-width=\"2.5\"/><path d=\"M21 14a7 7 0 0 0-7 7\" stroke-width=\"1.5\" stroke-opacity=\"0.6\"/>",
    "check": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/><path d=\"M14 24.5l7 7 13-14\" stroke-width=\"2.5\"/>",
    "circle": "<circle cx=\"24\" cy=\"24\" r=\"17\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/>",
    "half": "<circle cx=\"24\" cy=\"24\" r=\"17\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M24 7a17 17 0 0 1 0 34z\" fill=\"currentColor\" stroke=\"none\"/>",
    "alert": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/><path d=\"M24 13v14\" stroke-width=\"2.5\"/><circle cx=\"24\" cy=\"34\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\"/>",
    "close": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M16 16l16 16M32 16L16 32\" stroke-width=\"2.5\"/>",
    "plus": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M24 14v20M14 24h20\" stroke-width=\"2.5\"/>",
    "external": "<path d=\"M34 28v8a4 4 0 0 1-4 4H12a4 4 0 0 1-4-4V18a4 4 0 0 1 4-4h8\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M28 9h11v11\" stroke-width=\"2\"/><path d=\"M39 9L23 25\" stroke-width=\"2\"/>",
    "thumbsup": "<path d=\"M14 22v16a2.5 2.5 0 0 1-2.5 2.5H8A2.5 2.5 0 0 1 5.5 38V24.5A2.5 2.5 0 0 1 8 22z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M14 22l8.4-14.8a3.6 3.6 0 0 1 6.4 2.8L27 18h11.2a4 4 0 0 1 4 4.6l-2.2 13A4 4 0 0 1 36 40H14z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/>",
    "warning": "<path d=\"M20.6 8.6 3.6 38a4 4 0 0 0 3.4 6h34a4 4 0 0 0 3.4-6L27.4 8.6a4 4 0 0 0-6.8 0z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M24 19v9\" stroke-width=\"2.5\"/><circle cx=\"24\" cy=\"34.5\" r=\"1.7\" fill=\"currentColor\" stroke=\"none\"/>",
    "dot": "<circle cx=\"24\" cy=\"24\" r=\"18\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke=\"none\"/><circle cx=\"24\" cy=\"24\" r=\"9\" fill=\"currentColor\" stroke=\"none\"/>",
    "diamond": "<path d=\"M24 6l18 18-18 18L6 24z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/>",
    "diamondFilled": "<path d=\"M24 6l18 18-18 18L6 24z\" fill=\"currentColor\" fill-opacity=\"0.85\" stroke=\"currentColor\" stroke-width=\"2\"/>",
    "caretRight": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke=\"none\"/><path d=\"M20 13l13 11-13 11z\" fill=\"currentColor\" stroke=\"none\"/>",
    "arrowRight": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke=\"none\"/><path d=\"M11 24h24M26 14l10 10-10 10\" stroke-width=\"2.5\"/>",
    "square": "<rect x=\"8\" y=\"8\" width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\" fill-opacity=\"0.08\" stroke-width=\"2\"/>",
    "squareSplit": "<rect x=\"8\" y=\"8\" width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><rect x=\"17\" y=\"17\" width=\"14\" height=\"14\" rx=\"2.5\" fill=\"currentColor\" fill-opacity=\"0.85\" stroke=\"none\"/>",
    "squareRows": "<rect x=\"8\" y=\"8\" width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M8 18.7h32M8 29.3h32\" stroke-width=\"1.75\"/>",
    "squareCols": "<rect x=\"8\" y=\"8\" width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M18.7 8v32M29.3 8v32\" stroke-width=\"1.75\"/>",
    "squareGrid": "<rect x=\"8\" y=\"8\" width=\"32\" height=\"32\" rx=\"6\" fill=\"currentColor\" fill-opacity=\"0.06\" stroke-width=\"2\"/><path d=\"M24 8v32M8 24h32\" stroke-width=\"1.75\"/>",
    "rectangle": "<rect x=\"5\" y=\"16\" width=\"38\" height=\"16\" rx=\"4\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/>",
    "exchange": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M11 19h26l-7-7\" stroke-width=\"2.5\"/><path d=\"M37 29H11l7 7\" stroke-width=\"2.5\"/>",
    "wave": "<circle cx=\"24\" cy=\"24\" r=\"20\" fill=\"currentColor\" fill-opacity=\"0.05\" stroke=\"none\"/><path d=\"M7 24c3-8 8-8 11 0s8 8 11 0 8-8 11 0\" stroke-width=\"2.5\"/>",
    "pencil": "<path d=\"M9 39l2.5-8.5L31 11l6 6L17.5 36.5z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke-width=\"2\"/><path d=\"M27 15l6 6\" stroke-width=\"1.75\"/><path d=\"M9 39l2.5-8.5\" stroke-width=\"2\"/>",
}


def icon(name: str, cls: str | None = None) -> str:
    """Return a regular 24x24 icon as an inline `<svg class="ic ...">` string.

    Returns "" for unknown names (matches the council's previous `_icon`).
    `cls` appends an extra CSS class alongside any class baked into the icon.
    """
    spec = REGULAR.get(name)
    if spec is None:
        return ""
    classes = "ic"
    if spec.get("cls"):
        classes += " " + str(spec["cls"])
    if cls:
        classes += " " + cls
    return f'<svg class="{classes}" viewBox="0 0 24 24">{spec["body"]}</svg>'


def hifi(name: str, size: int = 48, cls: str = "ic-hifi") -> str:
    """Return a high-fidelity 48x48 display icon as a self-styled inline SVG."""
    body = HIFI.get(name)
    if body is None:
        return ""
    return (
        f'<svg class="{cls}" width="{size}" height="{size}" viewBox="0 0 48 48" '
        f'fill="none" stroke="currentColor" stroke-linecap="round" '
        f'stroke-linejoin="round" aria-hidden="true">{body}</svg>'
    )


def names() -> list[str]:
    return list(REGULAR.keys())


def hifi_names() -> list[str]:
    return list(HIFI.keys())
