/**
 * Codegen: deck.data.mjs → py/sonaloop_icons/deck.py
 *
 *   node scripts/gen-deck.mjs
 *
 * Emits the deck master template (palette, type scale, frame, layout catalogue and the
 * placeholder SAMPLE_SLIDES) as plain Python data for the python-pptx renderer. The app
 * vendors the module as sonaloop/_deck.py (scripts/sync_icons.sh), same as icons/tokens.
 * Fully generated — never edit the output by hand. No dependencies; runs on plain Node.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const { palette, frame, type, tones, layouts, deckTitle } = await import(resolve(root, 'deck.data.mjs'));

// JSON → Python literal (true/false/null → True/False/None); JSON.stringify gives us
// stable escaping, the replacements only touch bare literals (\b guards key collisions).
const py = (v) => JSON.stringify(v, null, 2)
  .replace(/\btrue\b/g, 'True')
  .replace(/\bfalse\b/g, 'False')
  .replace(/\bnull\b/g, 'None');

// PPTX colours are bare RRGGBB strings — strip the # once here, not in the renderer.
const hex = (h) => String(h).replace('#', '').toUpperCase();
const PALETTE = Object.fromEntries(Object.entries(palette).map(([k, v]) =>
  [k, Array.isArray(v) ? v.map(hex) : hex(v)]));

const LAYOUTS = layouts.map(({ key, title, desc }) => ({ key, title, desc }));
const SAMPLE_SLIDES = layouts.map((l) => l.sample);

const out = `"""sonaloop deck master template — GENERATED by sonaloop-design/scripts/gen-deck.mjs.

Do not edit by hand. Single source of truth: ../sonaloop-design/deck.data.mjs (layouts,
palette, type scale and the placeholder content). Vendored into the app as sonaloop/_deck.py
(see scripts/sync_icons.sh); sonaloop/_pptx.py renders every layout from these constants and
\`sonaloop template-deck\` renders SAMPLE_SLIDES into the demo deck. The docs site paints the
same data at #/deck, so preview and export cannot drift."""

# Colour roles, bare RRGGBB (python-pptx convention). PALETTE["series"] is the chart order.
PALETTE: dict = ${py(PALETTE)}

# Slide geometry (inches) + the shared frame coordinates every layout hangs off.
FRAME: dict = ${py(frame)}

# Role-based type scale (pt). "mono" selects the Geist Mono face in PPTX.
TYPE: dict = ${py(type)}

# Insight-family tones (mirrors the report's callout cards).
TONES: dict = ${py(tones)}

# The layout catalogue — every slide kind the master template defines, in deck order.
LAYOUTS: list = ${py(LAYOUTS)}

# Placeholder content for every layout — the fictitious "${deckTitle}" study. Each entry is
# the exact slide dict sonaloop/_pptx.render() accepts; together they are the demo deck.
DECK_TITLE: str = ${py(deckTitle)}
SAMPLE_SLIDES: list = ${py(SAMPLE_SLIDES)}
`;

const dst = resolve(root, 'py/sonaloop_icons/deck.py');
await writeFile(dst, out);
console.log(`wrote ${dst} (${out.length} bytes, ${layouts.length} layouts)`);
