/**
 * Codegen: deck.data.mjs → py/sonaloop_icons/deck.py + deck_assets.py
 *
 *   node scripts/gen-deck.mjs
 *
 * Emits the deck master template (palette, type scale, frame, layout catalogue and the
 * placeholder SAMPLE_SLIDES) as plain Python data for the python-pptx renderer, PLUS the
 * brand assets a deck embeds: PPTX can't take SVG, so the curated hi-fi icon set and the
 * brand logos are rasterized here at design time (sharp, devDependency) and the light
 * canvases recompressed — all baked as base64 into deck_assets.py (one line per asset),
 * the same vendor-as-base64 move as the pixel font. The app vendors both modules
 * (scripts/sync_icons.sh), same as icons/tokens. Fully generated — never edit by hand.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const { palette, frame, type, tones, layouts, deckTitle,
        deckIcons, deckIconTints, deckLogos, deckCanvases } = await import(resolve(root, 'deck.data.mjs'));
const { regular, hifi } = await import(resolve(root, 'icons.data.mjs'));

// JSON → Python literal (true/false/null → True/False/None); JSON.stringify gives us
// stable escaping, the replacements only touch bare literals (\b guards key collisions).
const py = (v) => JSON.stringify(v, null, 2)
  .replace(/\btrue\b/g, 'True')
  .replace(/\bfalse\b/g, 'False')
  .replace(/\bnull\b/g, 'None');

// PPTX colours are bare RRGGBB strings — strip the # once here, not in the renderer.
const hex = (h) => String(h).replace('#', '').toUpperCase();
const PALETTE = Object.fromEntries(Object.entries(palette).map(([k, v]) =>
  [k, Array.isArray(v) ? v.map(hex) : hex(v)]));

const LAYOUTS = layouts.map(({ key, title, desc }) => ({ key, title, desc }));
const SAMPLE_SLIDES = layouts.map((l) => l.sample);

const out = `"""sonaloop deck master template — GENERATED by sonaloop-design/scripts/gen-deck.mjs.

Do not edit by hand. Single source of truth: ../sonaloop-design/deck.data.mjs (layouts,
palette, type scale and the placeholder content). Vendored into the app as sonaloop/_deck.py
(see scripts/sync_icons.sh); sonaloop/_pptx.py renders every layout from these constants and
\`sonaloop template-deck\` renders SAMPLE_SLIDES into the demo deck. The docs site paints the
same data at #/deck, so preview and export cannot drift."""

# Colour roles, bare RRGGBB (python-pptx convention). PALETTE["series"] is the chart order.
PALETTE: dict = ${py(PALETTE)}

# Slide geometry (inches) + the shared frame coordinates every layout hangs off.
FRAME: dict = ${py(frame)}

# Role-based type scale (pt). "mono" selects the Geist Mono face in PPTX.
TYPE: dict = ${py(type)}

# Insight-family tones (mirrors the report's callout cards).
TONES: dict = ${py(tones)}

# The layout catalogue — every slide kind the master template defines, in deck order.
LAYOUTS: list = ${py(LAYOUTS)}

# Placeholder content for every layout — the fictitious "${deckTitle}" study. Each entry is
# the exact slide dict sonaloop/_pptx.render() accepts; together they are the demo deck.
DECK_TITLE: str = ${py(deckTitle)}
SAMPLE_SLIDES: list = ${py(SAMPLE_SLIDES)}
`;

const dst = resolve(root, 'py/sonaloop_icons/deck.py');
await writeFile(dst, out);
console.log(`wrote ${dst} (${out.length} bytes, ${layouts.length} layouts)`);

// ── deck_assets.py — rasterized brand assets (icons · logos · canvases) ──────────
const ICON_PX = 384;     // hi-fi icons render ≤1in on a slide; 384px keeps them crisp at 4×
const CANVAS_W = 1440;   // full-bleed 13.33in ⇒ ~108dpi; projection-grade, wheel-size-friendly

// hi-fi icon spec → standalone SVG → PNG (sharp). `color` resolves currentColor strokes/fills.
async function iconPng(spec, hex) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="${ICON_PX}" height="${ICON_PX}"`
    + ` fill="none" stroke="${hex}" color="${hex}" stroke-linecap="round" stroke-linejoin="round">${spec.body}</svg>`;
  return (await sharp(Buffer.from(svg)).png()).toBuffer();
}

// The deck embeds the ENTIRE hi-fi icon set (single source: icons.data.mjs `hifi`), so any icon
// the design system gains is immediately available to decks. `deckIcons` stays as the curated,
// recommended shortlist (surfaced first in pickers); the embed below is the full set.
const ICONS = {};
for (const name of Object.keys(hifi)) {
  const spec = hifi[name];
  if (!spec) throw new Error(`deck icon missing from hifi set: ${name}`);
  ICONS[name] = {};
  for (const tint of deckIconTints) {
    ICONS[name][tint] = (await iconPng(spec, palette[tint])).toString('base64');
  }
}
// Logos use the REGULAR icon set — the canonical .sl-logo lockup mark (24×24, stroke 1.75),
// not the hi-fi twin (user feedback: the deck logo must match the sidebar/website lockup).
async function logoPng(spec, hex) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="${ICON_PX}" height="${ICON_PX}"`
    + ` fill="none" stroke="${hex}" color="${hex}" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">${spec.body}</svg>`;
  return (await sharp(Buffer.from(svg)).png()).toBuffer();
}

const LOGOS = {};
for (const name of deckLogos) {
  const spec = regular[name];
  if (!spec) throw new Error(`deck logo missing from regular set: ${name}`);
  LOGOS[name] = (await logoPng(spec, palette.ink)).toString('base64');
}
const CANVASES = {};
for (const [name, file] of Object.entries(deckCanvases)) {
  const buf = await sharp(await readFile(resolve(root, 'images/canvas', file)))
    .resize({ width: CANVAS_W }).jpeg({ quality: 70, mozjpeg: true }).toBuffer();
  CANVASES[name] = buf.toString('base64');
}

const pyAsset = (obj) => JSON.stringify(obj, null, 0);  // one line per dict — LOC-bar-safe
const assetsOut = `"""sonaloop deck brand assets — GENERATED by sonaloop-design/scripts/gen-deck.mjs.

Do not edit by hand. Single source of truth: ../sonaloop-design (deck.data.mjs deckIcons/
deckLogos/deckCanvases + icons.data.mjs hifi specs + images/canvas). PPTX can't embed SVG,
so the curated icon set and logos are rasterized at design time (PNG, ${ICON_PX}px, accent/ink
tints) and the light canvases recompressed (JPEG, ${CANVAS_W}px wide). Vendored verbatim as
sonaloop/_deck_assets.py (scripts/sync_icons.sh); sonaloop/_pptx.py embeds them by name."""

# {icon: {tint: base64 PNG}} — the curated deck set (pillars \`icon:\` field).
ICONS: dict = ${pyAsset(ICONS)}

# {brand: base64 PNG} — ink-tinted marks for cover/closing.
LOGOS: dict = ${pyAsset(LOGOS)}

# {name: base64 JPEG} — light-theme painterly canvases (cover band, canvas-section).
CANVASES: dict = ${pyAsset(CANVASES)}
`;
const adst = resolve(root, 'py/sonaloop_icons/deck_assets.py');
await writeFile(adst, assetsOut);
console.log(`wrote ${adst} (${Math.round(assetsOut.length / 1024)} KB: ${Object.keys(ICONS).length} icons × ${deckIconTints.length} tints, ${Object.keys(LOGOS).length} logos, ${Object.keys(CANVASES).length} canvases)`);
