/**
 * Codegen: tokens.data.mjs → per-consumer token CSS.
 *
 *   node scripts/gen-tokens.mjs
 *
 * Outputs (both fully generated — never edit by hand):
 *   styles/tokens.css              R G B triplets, website var names (Tailwind)
 *   py/sonaloop_icons/tokens.py    hex CSS string, inspector var names (sonaloop app)
 *
 * No dependencies; runs on plain Node.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const { scales, website, inspector } = await import(resolve(root, 'tokens.data.mjs'));

// "#rrggbb" / "#rgb" → "r g b" (for Tailwind's rgb(var(--x) / <alpha>) pattern)
const hexToRgb = (hex) => {
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map((c) => c + c).join('');
  const n = parseInt(h, 16);
  return `${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255}`;
};

// ── website: styles/tokens.css (R G B triplets; [data-theme] driven, default light) ──
function genWebsiteCss() {
  const block = (obj) => Object.entries(obj).map(([k, v]) => `  --${k}: ${hexToRgb(v)};`).join('\n');
  return `/* GENERATED by sonaloop-design/scripts/gen-tokens.mjs from tokens.data.mjs. Do not edit.
   Single source of truth for colour. Values are R G B triplets so Tailwind opacity
   modifiers work: rgb(var(--ink) / 0.6). Edit tokens.data.mjs + \`npm run gen\` instead. */
:root,
[data-theme="light"] {
${block(website.light)}
}
[data-theme="dark"] {
${block(website.dark)}
}
`;
}

// ── inspector: py/sonaloop_icons/tokens.py (hex CSS string; :root + dark + [data-theme]) ──
function genInspectorPy() {
  const decls = (obj) => Object.entries(obj).map(([k, v]) => `--${k}:${v}`).join(';');
  const scaleDecls = Object.entries(scales).map(([k, v]) => `--${k}:${v}`).join(';');
  const light = decls(inspector.light);
  const dark = decls(inspector.dark);
  const css =
    `:root{${light};${scaleDecls}}\n` +
    `@media (prefers-color-scheme: dark){:root{${dark}}}\n` +
    `:root[data-theme="light"]{${light}}\n` +
    `:root[data-theme="dark"]{${dark}}\n`;
  return `"""sonaloop design tokens — GENERATED by sonaloop-design/scripts/gen-tokens.mjs.

Do not edit by hand. Single source of truth: ../sonaloop-design/tokens.data.mjs.
Vendored into the app as sonaloop/_tokens.py (see scripts/sync_icons.sh); web_assets.py
prepends TOKENS_CSS so one rewrite re-skins the whole app."""

TOKENS_CSS: str = ${JSON.stringify(css)}
`;
}

await writeFile(resolve(root, 'styles/tokens.css'), genWebsiteCss());
await writeFile(resolve(root, 'py/sonaloop_icons/tokens.py'), genInspectorPy());
console.log('generated design tokens:');
console.log('  → styles/tokens.css');
console.log('  → py/sonaloop_icons/tokens.py');
