/**
 * Codegen: icons.data.mjs → React barrel + Python module.
 *
 *   node scripts/gen.mjs
 *
 * Outputs (both fully generated — never edit by hand):
 *   src/index.ts                    React/TSX components for persona-website
 *   py/persona_icons/__init__.py    SVG-string helpers for persona-council
 *
 * No dependencies; runs on plain Node.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');

const { regular, hifi } = await import(resolve(root, 'icons.data.mjs'));

// Hand-authored hover-animation CSS, embedded verbatim into the Python package
// so persona-council and persona-website share one animation source.
const animCss = await readFile(resolve(root, 'styles/hifi-anim.css'), 'utf8');

// JSON string literals are valid in both TS and Python (double-quoted, escaped).
const lit = (s) => JSON.stringify(s);

// ── React barrel (src/index.ts) ──────────────────────────────────────────────
function genTs() {
  const lines = [];
  lines.push('/**');
  lines.push(' * persona-icons — GENERATED by scripts/gen.mjs. Do not edit.');
  lines.push(' * Source of truth: icons.data.mjs');
  lines.push(' *');
  lines.push(' *   import { SearchIcon, PersonaHifi } from \'persona-icons\'');
  lines.push(' *   <SearchIcon size={18} strokeWidth={1.75} className="text-slate-600" />');
  lines.push(' */');
  lines.push("import { personaIcon, personaIconHifi } from './icon';");
  lines.push(
    "export type { PersonaIcon, PersonaIconProps, PersonaIconHifiProps } from './icon';",
  );
  lines.push('');
  lines.push('// ── Regular 24×24 icons ──────────────────────────────────────────────────────');
  for (const [name, spec] of Object.entries(regular)) {
    lines.push(`export const ${spec.label} = personaIcon(${lit(spec.label)}, ${lit(spec.body)}, ${lit(name)});`);
  }
  lines.push('');
  lines.push('// ── High-fidelity 48×48 icons ────────────────────────────────────────────────');
  for (const [name, spec] of Object.entries(hifi)) {
    lines.push(
      `export const ${spec.label} = personaIconHifi(${lit(spec.label)}, ${lit(spec.body)}, ${lit(name)});`,
    );
  }
  lines.push('');
  return lines.join('\n');
}

// ── Python module (py/persona_icons/__init__.py) ─────────────────────────────
function genPy() {
  const reg = Object.entries(regular)
    .map(([name, s]) => `    ${lit(name)}: {"body": ${lit(s.body)}, "cls": ${s.cls ? lit(s.cls) : 'None'}},`)
    .join('\n');
  const hi = Object.entries(hifi)
    .map(([name, s]) => `    ${lit(name)}: ${lit(s.body)},`)
    .join('\n');

  return `"""persona-icons — GENERATED by scripts/gen.mjs. Do not edit.

Source of truth: ../../icons.data.mjs

Single icon library shared with persona-website (React). Here it renders to
SVG-string markup for server-rendered HTML.

    from persona_icons import icon, hifi
    icon("search")        # -> '<svg class="ic" viewBox="0 0 24 24">...</svg>'
    icon("star")          # -> '<svg class="ic star" ...>'  (extra class from data)
    hifi("persona", 64)   # -> standalone 64px display icon

Regular icons carry geometry only; stroke/size come from the host CSS rule
\`svg.ic\` (persona-council ships one). Hifi icons inline their own stroke
attributes so they render without any CSS.
"""

from __future__ import annotations

__all__ = [
    "REGULAR", "HIFI", "HIFI_ANIM_CSS",
    "icon", "hifi", "hifi_anim_css", "names", "hifi_names",
]

# name -> {"body": inner SVG markup, "cls": optional extra CSS class}
REGULAR: dict[str, dict[str, str | None]] = {
${reg}
}

# name -> inner SVG markup (48x48, self-styled)
HIFI: dict[str, str] = {
${hi}
}

# Optional hover-animation CSS (source: ../../styles/hifi-anim.css). Inline this
# into a <style> block to animate hi-fi icons on hover/focus; it is inert unless
# included, and self-disables under prefers-reduced-motion.
HIFI_ANIM_CSS: str = ${lit(animCss)}


def icon(name: str, cls: str | None = None, animate: bool = False) -> str:
    """Return a regular 24x24 icon as an inline \`<svg class="ic ...">\` string.

    Returns "" for unknown names (matches the council's previous \`_icon\`).
    \`cls\` appends an extra CSS class alongside any class baked into the icon.
    \`animate=True\` adds \`pi-animate\` so the optional hover animation applies.
    """
    spec = REGULAR.get(name)
    if spec is None:
        return ""
    classes = f"ic pi pi-{name}"
    if spec.get("cls"):
        classes += " " + str(spec["cls"])
    if animate:
        classes += " pi-animate"
    if cls:
        classes += " " + cls
    return f'<svg class="{classes}" viewBox="0 0 24 24">{spec["body"]}</svg>'


def hifi(name: str, size: int = 48, cls: str = "ic-hifi", animate: bool = False) -> str:
    """Return a high-fidelity 48x48 display icon as a self-styled inline SVG.

    \`animate=True\` adds \`pi-animate\` so the optional hover animation applies.
    """
    body = HIFI.get(name)
    if body is None:
        return ""
    klass = f"{cls} pi-hifi pi-hifi-{name}"
    if animate:
        klass += " pi-animate"
    return (
        f'<svg class="{klass}" width="{size}" height="{size}" '
        f'viewBox="0 0 48 48" fill="none" stroke="currentColor" '
        f'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{body}</svg>'
    )


def hifi_anim_css() -> str:
    """Return the hi-fi hover-animation CSS to inline in a <style> block."""
    return HIFI_ANIM_CSS


def names() -> list[str]:
    return list(REGULAR.keys())


def hifi_names() -> list[str]:
    return list(HIFI.keys())
`;
}

await writeFile(resolve(root, 'src/index.ts'), genTs());
await mkdir(resolve(root, 'py/persona_icons'), { recursive: true });
await writeFile(resolve(root, 'py/persona_icons/__init__.py'), genPy());

console.log(
  `generated: ${Object.keys(regular).length} regular + ${Object.keys(hifi).length} hifi icons`,
);
console.log('  → src/index.ts');
console.log('  → py/persona_icons/__init__.py');
